### ISSUE TITLE
ResolvePackageNotFound:   when running conda env create

### ISSUE THREAD

**Issue by luckyhug** [EliasNehme/Deep-STORM#2]
conda env create -f environment.yml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - icc_rt=2019.0.0
  - intel-openmp=2019.5
  - wincertstore=0.2
  - vs2015_runtime=14.16.27012
  - vc=14.1

should I delete the version number and try again?

**Comment by EliasNehme** [comment]
Hi, Sorry missed this!
Yes, try to install the versions that are available and see whether it runs or not. 
Alternatively, you can use the Colab notebook to skip the installation all together.
